apiVersion: apps/v1
kind: Deployment

metadata:
  name: myapp-devops-deployment
  labels:
    app: myapp
    type: front-end
spec:
   template:
      metadata:
        name: myapp-devops
        labels:
          app: myapp
          type: front-end

      spec:
        containers:
         - name: flask-container
           image: pavelinux/devops
           ports:
           - containerPort: 5000

   replicas: 3  
   selector: 
     matchLabels:
       app: myapp
