apiVersion: v1
kind: Service

metadata:
  name: myapp-devops-service

spec:
   type: NodePort
   ports:
     - targetPort: 5000
       port: 5000
       nodePort: 32767
   selector:
      app: myapp
      type: front-end
